# Generated by Django 6.0.1 on 2026-02-10 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_to_vocab_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson_content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_to_lessons',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
