# Generated by Django 6.0.1 on 2026-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_lesson_content_created_at_lesson_content_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='translation',
            new_name='status',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='translation_cn',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='translation_eng',
            field=models.CharField(default='', max_length=255),
        ),
    ]
