# Generated by Django 6.0.1 on 2026-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_translation_vocabulary_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='translation_cn',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='translation_eng',
            field=models.CharField(max_length=255),
        ),
    ]
