# Generated by Django 6.0.1 on 2026-06-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_vocabulary_translation_cn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_to_vocab',
            name='status',
            field=models.CharField(default='learning', max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='status',
            field=models.CharField(default='learning', max_length=255),
        ),
    ]
