# Generated by Django 6.0.1 on 2026-06-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_to_vocab_status_alter_vocabulary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='status',
            field=models.CharField(default='learning', max_length=255, null=True),
        ),
    ]
