# Generated by Django 6.0.1 on 2026-06-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_vocabulary_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='status',
        ),
    ]
