# Generated by Django 6.0.1 on 2026-06-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_vocabulary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='difficulty',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
