# Generated by Django 6.0.1 on 2026-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_user_session_key_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
