# Generated by Django 6.0.1 on 2026-02-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_to_vocab',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
